### ISSUE TITLE
Receiving deferred messages in ReceiveAndDelete mode doesn't remove the messages from Queues without settling

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-service-bus-go#126]
Sample Code: https://gist.github.com/ramya-rao-a/dc8dc7f6b9c2573995f7531cccedd507

Steps:
- Send a message
- Receive and defer the message
- Receive the deferred message in ReceiveAndDelete mode

Expected:
- Deferred Message to be removed from the queue

Actual:
- Deferred Message stays in the queue until settled explicitly

**Comment by devigned** [comment]
@ramya-rao-a have you been able to achieve this with the JS / TS lib? 

Here's what the code should look like for defer with receive and delete, but defer doesn't seem to handle receive and delete properly. The test code below fails since the queue still says there's 1 message left to process.

https://github.com/Azure/azure-service-bus-go/blob/d960efc2286827a16a072a7fbc1a025ad7f51983/queue_test.go#L735-L780

**Comment by richardpark-msft** [comment]
Hi @ramya-rao-a,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

I tried to replicate your initial issue using the latest azservicebus package - the scenario works correctly. I'll be pushing out a PR to include it in our normal test suite as well.

Thank you for submitting this, and I hope you find yourself working more with Service Bus in the future!
