### ISSUE TITLE
Auto Lock Renewal

### ISSUE THREAD

**Issue by marstr** [Azure/azure-service-bus-go#68]
While we expose the ability to renew message and session locks, at the moment it's on the user to schedule goroutines that will keep those locks.

**Comment by devigned** [comment]
related #118

**Comment by richardpark-msft** [comment]
Hi @marstr, agreed this would be useful.

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

I have an issue tracking this feature: https://github.com/Azure/azure-sdk-for-go/issues/15745

I'll link from there to here, because having a separate utility might be interesting, separate from the Processor type being discussed.
